HQ = GROUP:FindByName("HQ")
CC = COMMANDCENTER:New( HQ , "HQ")
FACGroup = SET_GROUP:New():FilterPrefixes( "FAC" ):FilterStart()
Detection = DETECTION_AREAS:New( FACGroup , 1000 )
Attack = SET_GROUP:New()
Attack:AddGroupsByName({"AV-8B", "AV8B - Naval", "F-14B", "F-14B - Naval", "F/A-18C", "F/A-18C - Naval", "M-2000C", "F-5E", "A-10C"})

Designate = DESIGNATE:New( CC, Detection, Attack )
Designate:SetThreatLevelPrioritization(true)
Designate:GenerateLaserCodes()
Designate:SetAutoLase( true )